### ISSUE TITLE
🚨 Potential Security Vulnerability

### ISSUE THREAD

**Issue by x3rz** [nebulade/meemo#107]
Hello Developers,
I have found a potential security vulnerability in your project that I reported on huntr.dev, as reports are confidential which, can only be seen by maintainers and researcher. so please visit and validate.
https://www.huntr.dev/bounties/1624646276745-nebulade/meemo/

**Comment by nebulade** [comment]
Hi and thanks for reporting. I am just not sure this is really applicable here. I can see the issue for the demo instance as such, but otherwise, which I think would be the real issue, the input/notes are personal and I am not sure it makes sense to attack yourself by using that trick.

But maybe I don't see how it would allow others to exploit that, can you give an example?

**Comment by x3rz** [comment]
Sure in the scenario if someone hosting this on the web giving access to write notes to others then they can execute malicious js on anyone who visits that vulnerable note.
Also in note sharing, if a user shared a note with a malicious payload then again execution of javascript 
The best approach is to sanitize the user input or using DOMpurify

**Comment by nebulade** [comment]
For transparency and context, as well as I don't deem this as critical, given the kind of app we are talking about, the code currently allows any HTML content to be put in notes, which in turn means, one can add the following to run javascript when a note is viewed:
```
This is note content <iframe src=javascript:alert(1) width=0 height=0 style=display:none;></iframe>
```

**Comment by x3rz** [comment]
yes but like other markdown notes creators they don't allow javascript to get executed as for example obsidian does allow all the HTML tags but it sanitizes the user input which prevents it from javascript execution.

**Comment by gramakri** [comment]
One case I can think is if I mindlessly copy/pasted some text from elsewhere into meemo notes and this ends up executing some unwanted script. I am not 100% sure what malicious things a javascript on a page can do though.

**Comment by nebulade** [comment]
`script` tags are not evaluated, so this is pretty much an `iframe` case here. I will see how to filter those out then.

**Comment by x3rz** [comment]
sure i can share about stored xss and things that can be done by it
https://blog.sqreen.com/stored-xss-explained/
https://portswigger.net/web-security/cross-site-scripting/stored
https://owasp.org/www-project-web-security-testing-guide/latest/4-Web_Application_Security_Testing/07-Input_Validation_Testing/02-Testing_for_Stored_Cross_Site_Scripting
https://owasp.org/www-community/attacks/xss/

These have detailed explanation about stored XSS

**Comment by x3rz** [comment]
yes that's right it completely sanitizes other tags and markdown links but not iframe

**Comment by nebulade** [comment]
It now uses a fast client side HTML sanitizer https://github.com/jitbit/HtmlSanitizer

**Comment by x3rz** [comment]
Thank it was a quick fix and can you please validate my report on huntr.dev 
https://www.huntr.dev/bounties/1624646276745-nebulade/meemo/

**Comment by nebulade** [comment]
I have never used huntr and don't understand what they mean with set bounties nor do I really care, since this is just some open source project without any financial backing. Either way I've closed that now selecting the commit, hopefully you gain some points there or however they do things.

Personally I'd prefer to get a personal message without having to sign up for another service which I won't really use :-)

But mostly thanks a lot for raising this in the first place, that is the most important part.

**Comment by x3rz** [comment]
I completely understand your concern and thank you for the quick fix 
Also you dont have to login because they send magic link by which maintainers can validate reports via mail. So can you please check mail by security@huntr.dev 
Also these bounties help is to grow sir :)
